version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 4242:80
    environment:
      WORDPRESS_DB_HOST: mysqldb
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin1234
      WORDPRESS_DB_NAME: mysqldb
    volumes:
      - wordpress:/var/www/html
    networks:
      - fitavari_network

  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
      MYSQL_RANDOM_ROOT_PASSWORD: '1234ab'
    volumes:
      - db:/var/lib/mysql
    networks: 
      - fitavari_network

volumes:
  wordpress:
  db:
networks: 
  fitavari_network: