version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
        - POSTGRES_PASSWORD=sicheres123Passwort
    ports:
        - 5432:5432
    volumes:
        - .database/dbscripts:/docker-entrypoint-initdb.d
        - postgres_data:/var/lib/postgresql/data
    networks: 
        - fitavari_network
  
#  reverseproxy:
#    build:
#        context: ./reverseproxy
#        dockerfile: Dockerfile
#    ports:
#        - 80:80
#    links:
#        - quarkus
#    networks: 
#        - fitavari_network
#  quarkus:
volumes:
    postgres_data:
networks: 
    fitavari_network: