version: "3.1"

services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=sicheres123Passwort
    ports:
      - 5432:5432
    volumes:
      - ./database/dbscripts/:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fitavari_network

  # reverseproxy:
  #   build:
  #     context: ./reverseproxy
  #     dockerfile: Dockerfile
  #   ports:
  #     - 80:80
  #   links:
  #     - quarkus
  #   networks:
  #     - fitavari_network

  # quarkus:
  #   build:
  #     context: ../fitervari_backend
  #     dockerfile: src/main/docker/Dockerfile.native
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - fitavari_network
  # webpage:
  #   build:
  #     context: ./webpage
  #     dockerfile: Dockerfile
  #   ports:
  #     - 9933:80
  #   networks:
  #     - fitavari_network

  postgres-keycloak:
        image: postgres
        volumes:
            - postgres-keycloak_data:/var/lib/postgresql/data
        ports: 
            - 5435:5432
        environment:
            - POSTGRES_DB=keycloak
            - POSTGRES_USER=keycloak
            - POSTGRES_PASSWORD=password
        networks:
            - fitavari_network
  keycloak:
        image: jboss/keycloak
        environment:
            - DB_VENDOR=POSTGRES
            - DB_ADDR=postgres-keycloak
            - DB_PORT=5432
            - DB_DATABASE=keycloak
            - DB_USER=keycloak
            - DB_SCHEMA=public
            - DB_PASSWORD=password
            - KEYCLOAK_IMPORT=./tmp/keycloak/realm_v3.json
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
        ports:
            - 8180:8080
        volumes:
            - ./keycloak/:/tmp/keycloak
        networks:
            - fitavari_network
        depends_on:
            - postgres-keycloak

volumes:
  postgres_data:
  postgres-keycloak_data:
networks:
  fitavari_network:
