create table news_letter
(
    id       bigint generated by default as identity
        constraint news_letter_pkey
            primary key,
    body     varchar(255),
    imageurl varchar(255),
    title    varchar(255)
);

alter table news_letter
    owner to postgres;

create table person
(
    id            bigint generated by default as identity
        constraint person_pkey
            primary key,
    cash_customer boolean,
    is_trainer    boolean,
    join_date     date,
    keycloak_name varchar(255),
    member_till   date,
    name          varchar(255)
);

alter table person
    owner to postgres;

create table exercise
(
    id              bigint not null
        constraint exercise_pkey
            primary key,
    creation_date   timestamp,
    exercise_type   varchar(255),
    name            varchar(255),
    official_flag   boolean,
    standard_set_nr integer,
    creator_id      bigint
        constraint fk4igit9g8xemt78eb22an1s8p5
            references person
);

alter table exercise
    owner to postgres;

create table set
(
    id          bigint generated by default as identity
        constraint set_pkey
            primary key,
    distance    double precision not null,
    repetitions integer          not null,
    set_number  integer,
    time        double precision not null,
    type        varchar(255),
    weight      double precision not null,
    exercise_id bigint
        constraint fks2c1wtpaeccrl2ms0ul6iqt5t
            references exercise
);

alter table set
    owner to postgres;

create table workout
(
    id            bigint generated by default as identity
        constraint workout_pkey
            primary key,
    creation_date timestamp,
    name          varchar(255),
    official_flag boolean,
    creator_id    bigint
        constraint fkbg3quypgnltc0fea591y2qk6v
            references person
);

alter table workout
    owner to postgres;

create table workout2exercise
(
    id          bigint generated by default as identity
        constraint workout2exercise_pkey
            primary key,
    exercise_id bigint
        constraint fkpcd2f76q58dexunj72tpuseo9
            references exercise,
    workout_id  bigint
        constraint fkos9ee6rqxnaw62g07nsmgj5i9
            references workout
);

alter table workout2exercise
    owner to postgres;

create table workout_history
(
    id         bigint generated by default as identity
        constraint workout_history_pkey
            primary key,
    date       timestamp,
    person_id  bigint
        constraint fkcmg3jnjk3keh35m1ml572vod8
            references person,
    workout_id bigint
        constraint fks78qhekgj52iql4v5jh51eetv
            references workout
);

alter table workout_history
    owner to postgres;

create table exercise_history
(
    id                 bigint generated by default as identity
        constraint exercise_history_pkey
            primary key,
    exercise_id        integer,
    workout_history_id bigint
        constraint fkq7pfxtqabcrae91f7auxi9uvp
            references workout_history
);

alter table exercise_history
    owner to postgres;

create table set_history
(
    id                  bigint generated by default as identity
        constraint set_history_pkey
            primary key,
    distance            double precision not null,
    exercise_history_id bigint
        constraint fk9u5jjny2c2dr2cbhe7xf7b7jq
            references exercise_history,
    set_number          integer,
    time                double precision not null,
    weight              double precision not null
);

alter table set_history
    owner to postgres;

